<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Hmp.Devops.Tools.EnvironmentRemover.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Core" Version="1.51.0" />
    <PackageReference Include="Castle.Core" Version="5.2.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="10.0.2" />
    <PackageReference Include="Microsoft.CodeCoverage" Version="18.0.1" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.2" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.82.0" />
    <PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" Version="4.82.0" />
    <PackageReference Include="Microsoft.Net.Http.Headers" Version="10.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="Microsoft.TestPlatform.TestHost" Version="18.0.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.analyzers" Version="1.27.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="xunit.assert" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.9" />
    <PackageReference Include="Azure.Identity" Version="1.17.1" />
    <PackageReference Include="Azure.ResourceManager" Version="1.13.2" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.51.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Hmp.Devops.Tools.EnvironmentRemover/Hmp.Devops.Tools.EnvironmentRemover.csproj" />
  </ItemGroup>
</Project>
